[project]
name = "cetal-scopes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "paulrauecker", email = "paul.rauecker@gmx.at" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.2",
]



[tool.pytest.ini_options]
addopts = "-ra --cov=cetal_scope --cov-report=term-missing"
testpaths = ["tests"]
